# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:54
from __future__ import unicode_literals

import crowdly.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Serial Number')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=128, null=True)),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('last_people_count', models.IntegerField(default=0)),
                ('last_people_count_ts', models.DateTimeField(default=0)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, b'Inactive'), (1, b'Active')], default=0)),
                ('owners', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(crowdly.helpers.ModelDiffMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pp_count', models.IntegerField()),
                ('new_pp_count', models.IntegerField()),
                ('description', models.TextField(blank=True, default=b'')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdly.Device', verbose_name=b'Device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
