# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_people_count_ts',
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
