# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0003_auto_20170922_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crowdly.Location'),
            preserve_default=False,
        ),
    ]
