# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0004_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
