# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0005_location_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_pp_count', models.IntegerField()),
                ('new_pp_count', models.IntegerField()),
                ('description', models.TextField(blank=True, default=b'')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdly.Device', verbose_name=b'Device')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_count', models.IntegerField()),
                ('description', models.TextField(blank=True, default=b'')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdly.Location', verbose_name=b'Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventHistory',
        ),
    ]
