# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0006_auto_20170922_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='owners',
        ),
    ]
