# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdly', '0008_auto_20170922_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationowner',
            name='last_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
